/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
static yyconst short int yy_acclist[447] =
    {   0,
       88,   86,   87,   85,   86,   87,   85,   87,   86,   87,
       86,   87,   86,   87,   72,   86,   87,   73,   86,   87,
       86,   87,   77,   86,   87,   76,   86,   87,   80,   86,
       87,   78,   86,   87,   66,   86,   87,   86,   87,   67,
       86,   87,   82,   86,   87,   82,   86,   87,   82,   86,
       87,   82,   86,   87,   82,   86,   87,   74,   86,   87,
       75,   86,   87,   82,   86,   87,   82,   86,   87,   82,
       86,   87,   82,   86,   87,   82,   86,   87,   82,   86,
       87,   82,   86,   87,   82,   86,   87,   82,   86,   87,
       82,   86,   87,   82,   86,   87,   82,   86,   87,   82,

       86,   87,   82,   86,   87,   82,   86,   87,   70,   86,
       87,   71,   86,   87,   85,   65,   81,   83,   57,   80,
       68,   62,   64,   63,   82,   82,   82,   59,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   83,   79,   69,   58,   82,   60,   82,   61,
       82,   82,   37,   82,   82,   52,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,

       82,   82,   82,   82,   82,   35,   82,   82,   82,   82,
       82,   82,   56,   82,   54,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   41,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       84,   82,   82,   82,   82,   82,   44,   82,   17,   82,
       82,   36,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   49,   82,   82,   82,   82,   82,   82,   82,
       15,   82,   82,   82,   82,   82,   82,   82,   82,   47,
       82,   82,   34,   82,   82,   39,   82,   82,   82,   82,
       82,   10,   82,   33,   82,   82,   82,   82,   82,   32,

       82,   82,   84,    4,   82,   82,   20,   82,   13,   82,
       42,   82,   82,   31,   82,   82,   82,   46,   82,   82,
       82,   82,   82,   82,   14,   82,   82,   12,   82,   82,
       53,   82,   82,   82,   24,   82,   82,   82,   45,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   26,   82,
       82,   82,   82,   25,   82,   82,   82,   82,   40,   82,
        6,   82,   55,   82,   82,   82,   82,    2,   82,   82,
       82,    5,   82,   82,   82,   82,    8,   82,   82,   82,
       82,   82,   50,   82,   82,   82,   21,   82,   82,   43,
       82,   82,   16,   82,   82,    7,   82,   82,   82,    1,

       82,   82,   48,   82,    9,   82,   19,   82,   82,   82,
        3,   82,   82,   82,   82,   82,   82,   29,   82,   82,
       82,   27,   82,   82,   82,   82,   82,   18,   82,   82,
       38,   82,   23,   82,   30,   82,   11,   82,   82,   51,
       82,   82,   28,   82,   22,   82
    } ;

static yyconst short int yy_accept[326] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   13,   15,
       18,   21,   23,   26,   29,   32,   35,   38,   40,   43,
       46,   49,   52,   55,   58,   61,   64,   67,   70,   73,
       76,   79,   82,   85,   88,   91,   94,   97,  100,  103,
      106,  109,  112,  115,  116,  117,  117,  118,  119,  119,
      120,  120,  121,  121,  122,  123,  124,  125,  126,  127,
      128,  130,  131,  132,  133,  134,  135,  136,  137,  138,
      139,  140,  141,  142,  143,  144,  145,  146,  147,  148,
      149,  150,  151,  152,  153,  154,  155,  156,  157,  158,
      159,  160,  161,  162,  163,  164,  165,  166,  167,  168,

      169,  170,  171,  172,  173,  174,  174,  174,  175,  176,
      178,  180,  182,  183,  185,  186,  188,  189,  190,  191,
      192,  193,  194,  195,  196,  197,  198,  199,  200,  201,
      202,  203,  204,  205,  206,  208,  209,  210,  211,  212,
      213,  215,  217,  218,  219,  220,  221,  222,  223,  224,
      225,  226,  227,  228,  229,  230,  232,  233,  234,  235,
      236,  237,  238,  239,  240,  241,  242,  242,  243,  244,
      245,  246,  247,  249,  251,  252,  254,  255,  256,  257,
      258,  259,  260,  261,  262,  263,  265,  266,  267,  268,
      269,  270,  271,  273,  274,  275,  276,  277,  278,  279,

      280,  282,  283,  285,  286,  288,  289,  290,  291,  292,
      294,  296,  297,  298,  299,  300,  302,  303,  303,  304,
      306,  307,  309,  311,  313,  314,  316,  317,  318,  320,
      321,  322,  323,  324,  325,  327,  328,  330,  331,  333,
      334,  335,  337,  338,  339,  341,  342,  343,  344,  345,
      346,  347,  348,  349,  351,  352,  353,  354,  356,  357,
      358,  359,  361,  363,  365,  366,  367,  368,  370,  371,
      372,  374,  375,  376,  377,  379,  380,  381,  382,  383,
      385,  386,  387,  389,  390,  392,  393,  395,  396,  398,
      399,  400,  402,  403,  405,  407,  409,  410,  411,  413,

      414,  415,  416,  417,  418,  420,  421,  422,  424,  425,
      426,  427,  428,  430,  431,  433,  435,  437,  439,  440,
      442,  443,  445,  447,  447
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    1,    1,    1,    7,
        8,    9,    1,   10,   11,   12,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    1,   15,
       16,   17,    1,    1,   18,   19,   19,   20,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   21,   22,   19,
       19,   23,   19,   24,   19,   19,   19,   25,   19,   19,
       26,    1,   27,    1,   28,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   19,   45,   46,   47,   48,   49,   50,   51,
       52,   19,   53,    1,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1
    } ;

static yyconst short int yy_base[330] =
    {   0,
        0,    0,  354,  355,   53,   55,  337,  347,   53,  355,
      355,  342,  355,  355,   48,   52,  334,  333,  332,  326,
        0,  324,  322,  322,  355,  355,   34,   38,   36,   38,
       33,   47,   48,   45,   25,   41,   57,   61,   66,   61,
       76,  355,  355,   94,  355,  338,  355,    0,  333,  355,
      328,   94,  323,  355,  355,  355,  355,    0,  319,  314,
        0,  314,   71,  293,  303,   81,  297,  304,  301,  288,
      293,   86,  285,  279,  281,  279,  285,   90,  276,  282,
      287,   74,  289,  280,  289,  282,   88,  287,   93,  273,
      282,  272,  284,  281,  270,  268,  269,  271,   95,  278,

      261,  268,  267,  266,    0,  293,  122,  288,  355,    0,
        0,    0,  255,    0,  253,    0,  253,  268,  254,  253,
      255,  264,  252,  245,  249,  252,  246,  247,  249,  252,
      251,  243,  247,  248,    0,  238,  242,  249,  229,  230,
       96,    0,  238,  241,  242,   89,  232,  231,  237,  222,
      226,  234,  231,  234,  234,    0,  230,  216,  222,  227,
      221,  221,  225,  209,  215,  355,  131,  207,  216,  211,
      205,  217,    0,    0,  217,    0,  201,  218,  204,  198,
      201,  211,  214,  199,  210,    0,  192,  207,  190,  191,
      189,  197,    0,  193,  185,  186,  193,  196,  199,  190,

        0,  189,    0,  196,    0,  191,  190,  179,  180,    0,
        0,  174,  186,  184,  171,    0,  183,  206,  205,    0,
      171,    0,    0,    0,  181,    0,  169,  177,    0,  157,
      175,  158,  174,  176,    0,  168,    0,  166,    0,  159,
      168,    0,  150,  153,    0,  151,  166,  147,  150,  166,
      147,  152,  158,    0,  159,  137,  144,    0,  154,  157,
      153,    0,    0,    0,  151,  137,  151,    0,  134,  138,
        0,  142,  145,  144,    0,  143,  138,  128,  127,    0,
      125,  124,    0,  141,    0,  123,    0,  123,    0,  128,
      130,    0,  119,    0,    0,    0,  121,  130,    0,  117,

      118,  129,  112,  121,    0,  116,  116,    0,  102,   91,
       97,  108,    0,  105,    0,    0,    0,    0,   81,    0,
       49,    0,    0,  355,  144,   75,  147,  150,  153
    } ;

static yyconst short int yy_def[330] =
    {   0,
      324,    1,  324,  324,  324,  324,  324,  325,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  326,
      326,  326,  326,  326,  324,  324,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  324,  324,  324,  324,  325,  324,  327,  328,  324,
      324,  324,  324,  324,  324,  324,  324,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  327,  328,  328,  324,  324,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  324,  329,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  328,  328,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,    0,  324,  324,  324,  324,  324
    } ;

static yyconst short int yy_nxt[410] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
        4,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       22,   23,   21,   21,   24,   25,   26,   21,   27,   28,
       29,   30,   31,   32,   21,   21,   21,   21,   21,   33,
       34,   21,   35,   36,   37,   38,   39,   21,   40,   41,
       21,   21,   42,   43,   44,   44,   44,   44,   48,   51,
       52,   49,   53,   63,   64,   65,   69,   54,   71,   85,
       73,   86,   75,   66,   74,   77,   79,   58,   72,   67,
       68,   82,   70,   76,   80,   87,   78,   83,   88,   89,
       81,   91,   84,  101,   96,   44,   44,   92,   97,   90,

      323,   98,   99,  102,  103,   51,   52,   93,   94,  117,
      100,  104,   95,  113,  124,  139,  114,  118,  133,  140,
      145,  148,  134,  149,  146,  159,  125,  166,  193,  198,
      167,  126,  322,  127,  135,  160,  219,  199,  321,  167,
      320,  319,  318,  194,   46,  317,   46,  105,  316,  105,
      106,  106,  106,  218,  218,  218,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,

      271,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  107,  107,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  197,  196,  195,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,

      108,  107,  165,  164,  163,  162,  161,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  147,  144,  143,  142,
      141,  138,  137,  136,  132,  131,  130,  129,  128,  123,
      122,  121,  120,  119,  116,  115,  112,  111,  110,  109,
      108,  107,   47,   62,   61,   60,   59,   57,   56,   55,
       50,   47,   45,  324,    3,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324
    } ;

static yyconst short int yy_chk[410] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    6,    9,   15,
       15,    9,   16,   27,   27,   27,   28,   16,   29,   35,
       30,   35,   31,   27,   30,   32,   33,  326,   29,   27,
       27,   34,   28,   31,   33,   36,   32,   34,   36,   37,
       33,   38,   34,   40,   39,   44,   44,   38,   39,   37,

      321,   39,   39,   40,   41,   52,   52,   38,   38,   66,
       39,   41,   38,   63,   72,   82,   63,   66,   78,   82,
       87,   89,   78,   89,   87,   99,   72,  107,  141,  146,
      107,   72,  319,   72,   78,   99,  167,  146,  314,  167,
      312,  311,  310,  141,  325,  309,  325,  327,  307,  327,
      328,  328,  328,  329,  329,  329,  306,  304,  303,  302,
      301,  300,  298,  297,  293,  291,  290,  288,  286,  284,
      282,  281,  279,  278,  277,  276,  274,  273,  272,  270,
      269,  267,  266,  265,  261,  260,  259,  257,  256,  255,
      253,  252,  251,  250,  249,  248,  247,  246,  244,  243,

      241,  240,  238,  236,  234,  233,  232,  231,  230,  228,
      227,  225,  221,  219,  218,  217,  215,  214,  213,  212,
      209,  208,  207,  206,  204,  202,  200,  199,  198,  197,
      196,  195,  194,  192,  191,  190,  189,  188,  187,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  175,  172,
      171,  170,  169,  168,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  145,  144,  143,  140,  139,  138,  137,  136,
      134,  133,  132,  131,  130,  129,  128,  127,  126,  125,
      124,  123,  122,  121,  120,  119,  118,  117,  115,  113,

      108,  106,  104,  103,  102,  101,  100,   98,   97,   96,
       95,   94,   93,   92,   91,   90,   88,   86,   85,   84,
       83,   81,   80,   79,   77,   76,   75,   74,   73,   71,
       70,   69,   68,   67,   65,   64,   62,   60,   59,   53,
       51,   49,   46,   24,   23,   22,   20,   19,   18,   17,
       12,    8,    7,    3,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 5 "lexer.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "parser.tab.h"

extern YYSTYPE yylval;
#line 631 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 21 "lexer.l"


#line 785 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 325 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 355 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 23 "lexer.l"
{ return MISSION; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "lexer.l"
{ return LAUNCH; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "lexer.l"
{ return SUCCESS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "lexer.l"
{ return ABORT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "lexer.l"
{ return MODULE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "lexer.l"
{ return DEPLOY; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "lexer.l"
{ return EXTENDS; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "lexer.l"
{ return PUBLIC; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 32 "lexer.l"
{ return PRIVATE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 33 "lexer.l"
{ return THIS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 35 "lexer.l"
{ return TELEMETRY; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 "lexer.l"
{ return LIMIT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 37 "lexer.l"
{ return ALIAS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 38 "lexer.l"
{ return FLEET; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 39 "lexer.l"
{ return MODE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 41 "lexer.l"
{ return COMMAND; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 42 "lexer.l"
{ return BACK; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 43 "lexer.l"
{ return BROADCAST; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 44 "lexer.l"
{ return RECEIVE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 "lexer.l"
{ return ALARM; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 47 "lexer.l"
{ return VERIFY; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 48 "lexer.l"
{ return ELSE_VERIFY; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 49 "lexer.l"
{ return OTHERWISE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "lexer.l"
{ return ORBIT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "lexer.l"
{ return WHILE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "lexer.l"
{ return TIMES; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "lexer.l"
{ return SCENARIO; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "lexer.l"
{ return TRAJECTORY; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "lexer.l"
{ return FALLBACK; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "lexer.l"
{ return STAGE_SEP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "lexer.l"
{ return COAST; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 61 "lexer.l"
{ return WAIT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 62 "lexer.l"
{ return TICK; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 63 "lexer.l"
{ return ROOT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 64 "lexer.l"
{ return FLR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 65 "lexer.l"
{ return CEIL; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 66 "lexer.l"
{ return ABS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 67 "lexer.l"
{ return LOGARITHM; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 68 "lexer.l"
{ return SINE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 69 "lexer.l"
{ return COSINE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 70 "lexer.l"
{ return TAN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 71 "lexer.l"
{ return ASINE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 72 "lexer.l"
{ return ACOSINE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 73 "lexer.l"
{ return ATAN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 74 "lexer.l"
{ return PRIME; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 76 "lexer.l"
{ return COUNT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 77 "lexer.l"
{ return REAL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 78 "lexer.l"
{ return PRECISE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 79 "lexer.l"
{ return FLAG; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 80 "lexer.l"
{ return SYMBOL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 81 "lexer.l"
{ return VOIDSPACE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 83 "lexer.l"
{ return ADD; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 84 "lexer.l"
{ return MINUS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 85 "lexer.l"
{ return MUL; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 86 "lexer.l"
{ return DIVIDE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 87 "lexer.l"
{ return MOD; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 88 "lexer.l"
{ return POWER; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 90 "lexer.l"
{ return AND; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 91 "lexer.l"
{ return OR; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 92 "lexer.l"
{ return NOT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 93 "lexer.l"
{ return XOR; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 95 "lexer.l"
{ return LE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 96 "lexer.l"
{ return GE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 97 "lexer.l"
{ return EQ; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 98 "lexer.l"
{ return NEQ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 99 "lexer.l"
{ return LT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 100 "lexer.l"
{ return GT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 102 "lexer.l"
{ return ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return RETTYPE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 105 "lexer.l"
{ return LBRACE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return RBRACE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return LPAREN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return RPAREN; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return LBRACKET; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return RBRACKET; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return DOT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return COMMA; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return COLON; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 115 "lexer.l"
{
                      yylval.floatval = atof(yytext);
                      return FLOAT_LITERAL;
                   }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 120 "lexer.l"
{
                      yylval.intval = atoi(yytext);
                      return INT_LITERAL;
                   }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 125 "lexer.l"
{
                      yylval.str = strdup(yytext);
                      return STRING_LITERAL;
                   }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 130 "lexer.l"
{
                      yylval.str = strdup(yytext);
                      return IDENTIFIER;
                   }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 135 "lexer.l"
{ }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 137 "lexer.l"
{ }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 139 "lexer.l"
{ }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 141 "lexer.l"
{
      printf("LEXICAL ERROR at line %d: %s\n", yylineno, yytext);
  }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 145 "lexer.l"
ECHO;
	YY_BREAK
#line 1325 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 325 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 325 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 324);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 145 "lexer.l"

